### ISSUE TITLE
[bug] Deltaboard keeps visiting localhost back-end when deployed on a remote server

### ISSUE THREAD

**Issue by lencyforce** [delta-mpc/deltaboard#51]
**Describe the bug**
Deltaboard keeps visiting localhost back-end when deployed on a remote server

**To Reproduce**
1. Deploy Deltaboard on a remote server
2. Access Deltaboard using the remote IP address

**Expected behavior**
Deltaboard operates normally

**Screenshots**
![c734c0e55a80540c112ce0c1b88b4cd](https://user-images.githubusercontent.com/3778069/158289374-0c9f24c0-d930-440e-a011-fb0f377d4824.png)

**Comment by lencyforce** [comment]
The remote IP address should not be hard coded into the project. Instead use a relative URL which has the same domain as the browser uses to visit the frontend

**Comment by mh739025250** [comment]
A workaround:
use ssh local port forwarding
`ssh -fNt -L 8090:{your-server-ip}:8090 {your-server-ssh-name}`

or just edit your host file to make localhost resolved to your server ip.

**Comment by mh739025250** [comment]
fixed in commit https://github.com/delta-mpc/deltaboard/commit/aa13d3867e084ed9d82b03b47e9fff79ea7637d4
