### ISSUE TITLE
任务提交异常[bug]

### ISSUE THREAD

**Issue by alexfor** [delta-mpc/deltaboard#52]
任务提交以后，在任务中心显示状态为异常

1. 在playground里执行官方示例程序zh-horizontal-learning-task
2. 进入列表查看结果
![1](https://user-images.githubusercontent.com/12745290/158320988-ff428920-bb99-4b79-8887-9e43fb3ff19a.png)
![2](https://user-images.githubusercontent.com/12745290/158321116-8bdf4c07-f4d3-4cdf-9481-d2ede102026a.png)

**Comment by lencyforce** [comment]
the same to [delta-node#19](https://github.com/delta-mpc/delta-node/issues/19)
